### ISSUE TITLE
Processed Dataset Link Unavailable

### ISSUE THREAD

**Issue by kkkkk001** [yunzhusong/AARD#3]
The link to the processed dataset is unavailable. Could you please update the link? Thanks a lot.

**Comment by yunzhusong** [comment]
Hi, thank you for your interest and reminder. We have fixed the download link. If there is any other issue, please let me know. Thanks!

**Comment by kkkkk001** [comment]
> Hi, thank you for your interest and reminder. We have fixed the download link. If there is any other issue, please let me know. Thanks!

Thank you for your timely response and update!
